### ISSUE TITLE
Media queries not getting compiled

### ISSUE THREAD

**Issue by ghost** [BananaAcid/compile-superhero#2]
This code here: 

```scss
@import '_variables';

@media screen and (min-width: 768px) {
#main-div{
    $main-row-direction: column;
    $tribute-info-width: 100%;
 }
}
```

Won't get compiled, is this normal behaviour?

Thanks.
